application: docroo
version: 1 
runtime: python27
threadsafe: yes
api_version: 1
handlers:

- url: /
  static_files: _build/html/index.html
  upload: _build/html/index.html
#  secure: always
  login: admin

- url: /
  static_dir: _build/html
#  secure: always
  login: admin

- url: /(.*\.(gif|png|jpg|ico|js|css|html))
  static_files: /
  upload: _build/html/(.*\.(gif|png|jpg|ico|js|css|html))
#  secure: always
  login: admin

skip_files:
- ^parts
- ^bootstrap.py
- ^env$
- ^buildout.cfg
- ^downloads$
- ^eggs$
- ^bin$
- .installed.cfg
- develop-eggs
- ^venv

